# -*- coding: utf-8 -*-
"""Aula 1 Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18vT9Dr3vKmGRtrusLlJBCvOAfweuGie8

# Basicos
## o basico da Python


int (inteiro): Valor Numerico

float (flutuante): Valor Decimal

str (string): Texto
"""

print(10 % 4)

"""#Variaveis"""

fruta = "Banana"
nome = "Lan code"

print(fruta)
print(nome)

meu_nome = "Rodrigo"
print(meu_nome)

num1 = 8
num2 = 10
resultado = num1 + num2

print(resultado)

"""# Inputs"""

nome = input("qual seu nome? ")
idade = input("qual a sua idade? ")

print(f"o seu nome e {nome}, e sua idade e {idade}" )

"""# Exercicios

a. Crie um codigo que exiba a frase "Ola, estou aprendendo Python"

b. Crie um codigo que pede a idade e o nome do usuario, e exibe ambos

c. Peca ao usuario 2 numeros, e em seguida, exiba a soma e a subtracao
deles

# Exercicio A
"""

print("Ola, estou aprendendo Python")

"""# Exercicio B"""

nome = input("Qual e seu nome? ")
idade = input("Qual e sua idade? ")

print(f"Seu nome e {nome}, e sua idade e {idade}")

"""# Exercicio C"""

num1 = input("digite um numero ")
num2 = input("digite outro numero ")

print(f"A soma dos numeros e {int(num1) + int(num2)}")
print(f"e a subtracao dele e {int(num1) + int(num2)}")