# -*- coding: utf-8 -*-
"""Aula 2 Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ZPa-403TmgG9LZ5CryTa5FtGyKkJgnB

# If e Else
"""

idade = int(input("qual sua idade? "))
maior_de_idade = 18

if idade > maior_de_idade:
  print("Voce e maior de idade")
else:
  print("Voce e menor de idade")

"""# Operadores de comparacao"""

nota = float(input("digite sua nota: "))

if nota >= 6:
  print("Passou!")
  if nota >= 9:
    print("ETCHA MININ INTELIGEEEEEENTE MEU DEEUSSS")
if nota <=5:
  print("Reprovou!")

idade = 97

if idade < 13:
  print("crianca")
elif idade < 18:
  print("adolescente")
elif idade < 65:
  print("Adulto")
else:
  print("Idoso")

"""# Booleano"""

resultado = 10 < 5
print(resultado)

"""# Operadores Logicos"""

idade = 15
tem_carteira_motorista = True

if idade >= 18 and tem_carteira_motorista == True:
  print("Ce pode dirigir")
elif idade >= 18 and tem_carteira_motorista == False:
  print("Voce e maior de idade, mas nao pode dirigir")
elif idade < 18 and tem_carteira_motorista == True:
  print("Voce pode dirigir, mas apenas quando fizer 18 anos")
else:
  print("Voce nao e maior de idade, e nem tem carta, nao pode dirigir")

Estudante = False
Idoso = False

if Estudante or Idoso == True:
  print("Ganhou desconto")
else:
  print("Ganhou porra nenhuma kkkkkkk")

"""# Exercicios

a. Crie um programa, onde o preco do pao sera guardado em uma variavel. Apos isso, o usuario digitara quanto dinheiro ele tem. Caso ele tenha 
dinheiro o suficiente, uma mensagem dira que ele pode comprar o pao, caso contrario ele nao pode

b. Crie uma variavel "Temperatura" e exiba uma mensagem para cada tipo de temperatura dela, "Frio" e baixa, "Normal" e normal, e "Quente" e alta

c. Crie uma variavel "Horario", e exiba uma mensagem de cumprimento relativa ao horario... "Bom dia" "Boa tarde" "Boa noite"

d. Crie um programa para validar a entrada de um atleta, ele precisa ter entre 18 a 35 anos e um bom condicionamento físico ou permissão médica.
Tude deve ser feito em uma anica estrutura "if"
```
if idade_atleta >= 18 and (fasico_bom or permissao_medica) == True:
  print("pode participar")
else:
  print("pode nao fi")
```

# Exercicio A
"""

Preco_pao = 3.00
Conta_bancaria = float(input("Quanto dinheiro voce tem? "))

if Conta_bancaria >=Preco_pao:
  print("Voce pode comprar o pao")
else:
  print("Voce nao tem dinheiro o suficiente")

"""# Exercicio B"""

Temperatura = 18

if Temperatura < 15:
  print("Esta frio")
elif Temperatura < 30:
  print("Esta em temperatura media")
elif Temperatura < 45:
  print("Esta quente")
else:
  print("Esta MUITO quente")

"""# Exercicio C"""

Horario = 4

if Horario < 12 and Horario >= 6:
  print("bom dia")
elif Horario <=18:
  print("Boa tarde")
elif Horario <=24:
  print("Boa noite")
else:
  print("Boa madrugada")

"""# Exercicio D"""

idade_atleta = int(input("Qual a idade do atleta? "))
fisico_bom = False
permissao_medica = True

if idade_atleta >= 18 and idade_atleta <= 35:
  print("Ele esta na idade adequada")
  if fisico_bom or permissao_medica == True:
    print("Este permitido entrar")
  elif fisico_bom or permissao_medica == False:
    print("Nao esta permitido entrar")
else:
  print("Nao esta na idade adequada")

"FORMA ADEQUADA"

'''
if idade_atleta >= 18 and (fisico_bom or permissao_medica) == True:
  print("pode participar")
else:
  print("pode nao fi")

'''